str = '''Regular expressions are patterns used to match character combinations in strings. In JavaScript, regular expressions are also objects. These patterns are used with the exec() and test() methods of RegExp, and with the match(), matchAll(), replace(), replaceAll(), search(), and split() methods of String. This chapter describes JavaScript regular expressions.Regular expressions are patterns used to match character combinations in strings. In JavaScript, regular expressions are also objects. These patterns are used with the exec() and test() methods of RegExp, and with the match(), matchAll(), replace(), replaceAll(), search(), and split() methods of String. This chapter describes JavaScript regular expressions.Regular expressions are patterns used to match character combinations in strings. In JavaScript, regular expressions are also objects. These patterns are er@gmail.com used with the exec() and test() methods of RegExp, and with the match(), matchAll(), replace(), replaceAll(), search(), and split() methods of String. This chapter describes JavaScript regular expressions.Regular expressions are patterns used to match character combinations in strings. In JavaScript, regular expressions are also objects. These patterns are used with the exec() and test() methods of RegExp, Mahessdfas@gmail.com and with the match(), matchAll(), replace(), replaceAll(), search(), and split() methods of String. This chapter describes JavaScript regular expressions.Regular expressions are patterns used to match character combinations in strings. In JavaScript, Addfsaf29@gmail.com regular expressions are also objects. These patterns are used with the exec() and test() methods of RegExp, and with the match(), matchAll(), replace(), replaceAll(), search(), and split() methods of String. This chapter describes JavaScript regular expressions.Regular expressions are patterns used to match character combinations in strings. In JavaScript, regular expressions are also objects. These patterns are used with the exec() and test() methods of RegExp, and with the match(), matchAll(), replace(), sidhhu@gmail.com replaceAll(), search(), and split() methods of String. This chapter describes JavaScript regular expressions.

'''

import re

ls = re.findall(r'\w*@gmail.com', str)
# print(ls)

with open('email.txt', 'w') as file:
    file.write('email in files:\n')
    for i in ls:
        file.write(f"{i}\n")